# Basic config
base_url = "https://zefira.dev"
theme = "hermit"
default_language = "en"

# Feed info
title = "Zefira's Digital Garden"
description = "Out beyond ideas of wrongdoing and rightdoing there is a garden. Let us meet there and talk about code."

# Building Options
compile_sass = true
minify_html = true
generate_feed = true
build_search_index = true

[markdown]
# Code Syntax Highlighting
highlight_code = true
highlight_theme = "zenburn"

[extra]

author = { name = "Zefira Shannon", email = "zefira@hey.com" }

# Hermit theme config

hermit_menu = [
    { name = "About", link = "/about/me/" },
    { name = "Posts", link = "/posts/" },
]

hermit_social = [
    { name = "github", link = "https://github.com/RadicalZephyr" },
    { name = "twitter", link = "https://twitter.com/RadicalZephyr" },
    { name = "email", link = "mailto:zefira@hey.com" },
]
